### PR TITLE
Implement environment variable parsing.

### PR DESCRIPTION
**Pull request by chjj**
This seems to work in practice. Would be nice to have it in.

### CODE REVIEW

**Comment by TooTallNate** [comment]
JJ! Nice stuff man. We can probably remove line 104 now too.

**Comment by chjj** [comment]
Yeah, I'll do that. 

I was considering also implementing termtype, but it's not working yet since most servers have to respond with `IAC SB TERMINAL-TYPE SEND IAC SE` after the `IAC WILL TERMINAL-TYPE`. Might have to refactor some things. https://github.com/chjj/node-telnet/commit/833c73223e96c4ca361c093e53f1a08bd5241ded

**Comment by chjj** [comment]
This is pretty crucial now that blessed can work well over telnet. I want to see someone make a blessed+telnet mmorpg or something.

**Comment by TooTallNate** [comment]
Wow that would be awesome

**Comment by chjj** [comment]
Removed line 104.

**Comment by chjj** [comment]
Awesome. Thanks.

**Pull request merged**
