### PR TITLE
node-telnet - rewritten with improvements

### PR DESCRIPTION
**Pull request by chjj**
This is nearly a total rewrite but it keeps the same basic idea and is backwardly compatible with the original. It doesn't require any dependencies and can parse a stream byte-by-byte. It implements all known telnet options (standard or non-standard) and handles them accordingly if there's not already a handler. It supports NEW_ENVIRON and TERMINAL_TYPE.

I was originally going to move this to a separate project since it changed so much, but maybe it would fit here.

@TooTallNate, thoughts?

### CODE REVIEW

**Comment by TooTallNate** [comment]
@chjj This is awesome! We should squash and merge. What's up with the failing tests?

**Comment by chjj** [comment]
Oh, I thought that was just the node v0.8.x failure. Hmm, must be some backward compat issue. I'll fix it soon.

**Comment by chjj** [comment]
@TooTallNate, should be fixed now. The new server object just wasn't proxying events properly. Just a simple fix.

**Comment by chjj** [comment]
Also, I've been working on implementing SRP, but it's still really in its early stages. I'm not even sure how many telnet clients support it anyway.

**Comment by chjj** [comment]
@TooTallNate,

Any word on this? I'd really like to get this in.

**Comment by chjj** [comment]
@TooTallNate, I went ahead and released node-telnet2 for now: https://github.com/chjj/node-telnet2

**Comment by TooTallNate** [comment]
@chjj Shoot, sorry I let this one slip by. I did end up giving you commit bits to this project a couple weeks ago but I think I forgot to mention it.

So I'm :+1: for merging, I'll get to it soon but feel free to go ahead and do it yourself if you feel up to it! :dancers:

**Comment by chjj** [comment]
Cool. I'll merge it. Is there any chance we could release it on npm?

**Pull request merged**
